// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYnz-_-Ca7ihOL4nymyndA5GcnnT9LERc',
    appId: '1:768635122392:web:62edfdf03332a8fe769dad',
    messagingSenderId: '768635122392',
    projectId: 'a91a05b5-ab6a7',
    authDomain: 'a91a05b5-ab6a7.firebaseapp.com',
    storageBucket: 'a91a05b5-ab6a7.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBz66RG7LmSo4O62ybEDd8faktohDvoJhs',
    appId: '1:768635122392:android:f95d9a166fe1ae8f769dad',
    messagingSenderId: '768635122392',
    projectId: 'a91a05b5-ab6a7',
    storageBucket: 'a91a05b5-ab6a7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAe9sbKDOcRnrCmyFM61OulhIz08pb_xb0',
    appId: '1:768635122392:ios:45b93eb04ce4f566769dad',
    messagingSenderId: '768635122392',
    projectId: 'a91a05b5-ab6a7',
    storageBucket: 'a91a05b5-ab6a7.firebasestorage.app',
    iosBundleId: 'com.example.busTracking',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAe9sbKDOcRnrCmyFM61OulhIz08pb_xb0',
    appId: '1:768635122392:ios:45b93eb04ce4f566769dad',
    messagingSenderId: '768635122392',
    projectId: 'a91a05b5-ab6a7',
    storageBucket: 'a91a05b5-ab6a7.firebasestorage.app',
    iosBundleId: 'com.example.busTracking',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDYnz-_-Ca7ihOL4nymyndA5GcnnT9LERc',
    appId: '1:768635122392:web:a9a20bec389c3116769dad',
    messagingSenderId: '768635122392',
    projectId: 'a91a05b5-ab6a7',
    authDomain: 'a91a05b5-ab6a7.firebaseapp.com',
    storageBucket: 'a91a05b5-ab6a7.firebasestorage.app',
  );
}
